library(shiny)

shinyUI(pageWithSidebar(
  headerPanel("Multivariate regression and variable correlation"),
  sidebarPanel(
    h4("User input"),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    h4("Select variables for regression"),
    p("By clicking on the checkboxes below, select which variables you want to use in the regression calculation:"),  
    checkboxGroupInput("vars", 
                       label = h6("Variables"), 
                       choices = list("Agriculture" = 2, 
                                      "Examination" = 3,
                                      "Education" = 4,
                                      "Catholic" = 5,
                                      "Infant Mortality" = 6),
                       selected = 2),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  br(),
  h4("Correlation"),
  p("To investigate the dataset further, you can check if variables are correlated."),
  
  selectInput("select1", label = h5("Calculate correlation between variable:"), 
              choices = list("Agriculture" = 2,
                             "Examination" = 3,
                             "Education" = 4,
                             "Catholic" = 5,
                             "Infant.Mortality" = 6)),
  selectInput("select2", label = h5("and"), 
              choices = list("Agriculture" = 2, 
                             "Examination" = 3,
                             "Education" = 4,
                             "Catholic" = 5,
                             "Infant.Mortality" = 6))
    ),
  mainPanel(
    p("The purpose of this application is to teach new users how to use Multivariate regression and to show them how correlated variables influence the result."),
    p("This application is part of Course Project for Developing Data Products, which is part of Data Science Specialization."),
    p("The class is taught by Brian Caffo of Johns Hopkins, and is operated by Coursera."),
    p("The lectures from another course from the Specialization, 'Regression Models', were used to produce this application."),
    h4('Multivariate regression'),
    p("This data is located in the 'swiss' dataset, in the 'datasets' package. The data was gathered in 1888, a time of demographic change in Switzerland, and measured six quantities
 in 47 French-speaking provinces of Switzerland."),
    a("More info about the dataset and its variables", href="http://www.inside-r.org/r-doc/datasets/swiss"),
    p("The goal is to predict Fertility using a subset of the other variables."),
    p("You can select which variables you want to include in the regression function by selecting them on the left panel:"),
    h5('Summary of the regression function:'),
    verbatimTextOutput("fit"),
    
    h4('Correlation'),    
    p("Try out different configurations by including and excluding different variables in the regression function."),
    p("You'll be able to see that the variable estimates change with changes to the configuration, but sometimes the estimates even change their sign!"),
    p("This happens because of the correlation that exists between some of the variables."),
    p("You can find out what the correlation between the variables is by using the drop-down lists on the left panel:"),
    p("Correlation has values from -1 to 1. You will notice that correlation between a variable and itself is 1."),
    h5('The correlation between the selected two variables is:'),
    verbatimTextOutput("cor"),
    plotOutput('corPlot'),
    p("Author: Vladimir Jovanovic"),
    p("Date: 25.01.2015.")
    )
  ))